version: 2.1

jobs:
  build-percy-docker:
    machine: true
    parameters:
      php_version:
        type: string
      ruby_version:
        type: string
    steps:
      - checkout
      - run: docker build --tag itinerisltd/circleci-percy-anywhere-wp:php-<< parameters.php_version >>-ruby-<< parameters.ruby_version >> --build-arg PHP_VERSION=<< parameters.php_version >> --build-arg RUBY_VERSION=<< parameters.ruby_version >> src/percy
      - run: echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - run: docker push itinerisltd/circleci-percy-anywhere-wp:php-<< parameters.php_version >>-ruby-<< parameters.ruby_version >>

workflows:
  build-percy-docker-nightly:
    triggers:
      - schedule:
          # Every day at 12am UTC
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build-percy-docker:
          name: php-7.3-ruby-2.6.1
          php_version: '7.3'
          ruby_version: '2.6.1'
      - build-percy-docker:
          name: php-7.3-ruby-2.6.0
          php_version: '7.3'
          ruby_version: '2.6.0'
      - build-percy-docker:
          name: php-7.2-ruby-2.6.1
          php_version: '7.2'
          ruby_version: '2.6.1'
      - build-percy-docker:
          name: php-7.2-ruby-2.6.0
          php_version: '7.2'
          ruby_version: '2.6.0'

  build-percy-docker-on-push:
    jobs:
      - build-percy-docker:
          name: php-7.3-ruby-2.6.1
          php_version: '7.3'
          ruby_version: '2.6.1'
          filters:
            branches:
              only: master
      - build-percy-docker:
          name: php-7.3-ruby-2.6.0
          php_version: '7.3'
          ruby_version: '2.6.0'
          filters:
            branches:
              only: master
      - build-percy-docker:
          name: php-7.2-ruby-2.6.1
          php_version: '7.2'
          ruby_version: '2.6.1'
          filters:
            branches:
              only: master
      - build-percy-docker:
          name: php-7.2-ruby-2.6.0
          php_version: '7.2'
          ruby_version: '2.6.0'
          filters:
            branches:
              only: master
