version: 2.1

jobs:
  build-percy-anywhere-wp-docker:
    machine: true
    parameters:
      php_version:
        type: string
      ruby_version:
        type: string
    steps:
      - checkout
      - run: docker build --tag itinerisltd/percy-anywhere-wp:php-<< parameters.php_version >>-ruby-<< parameters.ruby_version >> --build-arg PHP_VERSION=<< parameters.php_version >> --build-arg RUBY_VERSION=<< parameters.ruby_version >> src/percy-anywhere-wp
      - run: echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - run: docker push itinerisltd/percy-anywhere-wp:php-<< parameters.php_version >>-ruby-<< parameters.ruby_version >>

  build-tiller-circleci-docker:
    machine: true
    parameters:
      node_version:
        type: string
    steps:
      - checkout
      - run: docker build --tag itinerisltd/tiller-circleci:node-<< parameters.node_version >> --build-arg NODE_VERSION=<< parameters.node_version >> src/tiller-circleci
      - run: echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - run: docker push itinerisltd/tiller-circleci:node-<< parameters.node_version >>

workflows:
  build-docker-nightly:
    triggers:
      - schedule:
          # Every day at 12am UTC
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build-percy-anywhere-wp-docker:
          name: php-7.3-ruby-2.6.1-percy-anywhere-wp
          php_version: '7.3'
          ruby_version: '2.6.1'
      - build-percy-anywhere-wp-docker:
          name: php-7.3-ruby-2.6.0-percy-anywhere-wp
          php_version: '7.3'
          ruby_version: '2.6.0'
      - build-percy-anywhere-wp-docker:
          name: php-7.2-ruby-2.6.1-percy-anywhere-wp
          php_version: '7.2'
          ruby_version: '2.6.1'
      - build-percy-anywhere-wp-docker:
          name: php-7.2-ruby-2.6.0-percy-anywhere-wp
          php_version: '7.2'
          ruby_version: '2.6.0'

      - build-tiller-circleci-docker:
          name: node-11-tiller-circleci
          node_version: '11'
      - build-tiller-circleci-docker:
          name: node-10-tiller-circleci
          node_version: '10'
      - build-tiller-circleci-docker:
          name: node-8-tiller-circleci
          node_version: '8'

  build-docker-on-push:
    jobs:
      - build-percy-anywhere-wp-docker:
          name: php-7.3-ruby-2.6.1-percy-anywhere-wp
          php_version: '7.3'
          ruby_version: '2.6.1'
          filters:
            branches:
              only: master
      - build-percy-anywhere-wp-docker:
          name: php-7.3-ruby-2.6.0-percy-anywhere-wp
          php_version: '7.3'
          ruby_version: '2.6.0'
          filters:
            branches:
              only: master
      - build-percy-anywhere-wp-docker:
          name: php-7.2-ruby-2.6.1-percy-anywhere-wp
          php_version: '7.2'
          ruby_version: '2.6.1'
          filters:
            branches:
              only: master
      - build-percy-anywhere-wp-docker:
          name: php-7.2-ruby-2.6.0-percy-anywhere-wp
          php_version: '7.2'
          ruby_version: '2.6.0'
          filters:
            branches:
              only: master

      - build-tiller-circleci-docker:
          name: node-11-tiller-circleci
          node_version: '11'
          filters:
            branches:
              only: master
      - build-tiller-circleci-docker:
          name: node-10-tiller-circleci
          node_version: '10'
          filters:
            branches:
              only: master
      - build-tiller-circleci-docker:
          name: node-8-tiller-circleci
          node_version: '8'
          filters:
            branches:
              only: master
