version: 2.1

orbs:
  circleci-cli: circleci/circleci-cli@0

jobs:
  vaildate-orb:
    executor: circleci-cli/default
    parameters:
      orb_path:
        type: string
    steps:
      - checkout
      - run: circleci version
      - run: circleci orb validate << parameters.orb_path >>

  build-percy-cypress-wp-docker:
    machine: true
    parameters:
      php_version:
        type: string
      docker_user:
        type: env_var_name
        default: DOCKER_USER
      docker_pass:
        type: env_var_name
        default: DOCKER_PASS
    steps:
      - checkout
      - run: docker build --tag itinerisltd/percy-cypress-wp:chrome69-php-<< parameters.php_version >> --build-arg PHP_VERSION=<< parameters.php_version >> src/percy-cypress-wp
      - run: echo ${<< parameters.docker_pass >>} | docker login --username ${<< parameters.docker_user >>} --password-stdin
      - run: docker push itinerisltd/percy-cypress-wp:chrome69-php-<< parameters.php_version >>

  build-tiller-circleci-docker:
    machine: true
    parameters:
      node_version:
        type: string
      docker_user:
        type: env_var_name
        default: DOCKER_USER
      docker_pass:
        type: env_var_name
        default: DOCKER_PASS
    steps:
      - checkout
      - run: docker build --tag itinerisltd/tiller-circleci:node-<< parameters.node_version >> --build-arg NODE_VERSION=<< parameters.node_version >> src/tiller-circleci
      - run: echo ${<< parameters.docker_pass >>} | docker login --username ${<< parameters.docker_user >>} --password-stdin
      - run: docker push itinerisltd/tiller-circleci:node-<< parameters.node_version >>

# Wait for https://discuss.circleci.com/t/workflows-seem-incomplete/13461
only-master-filter: &only-master-filter
  filters:
    branches:
      only: master

build-docker-workflow: &build-docker-workflow
  jobs:
    - build-percy-cypress-wp-docker:
        <<: *only-master-filter
        name: chrome69-php7.3-percy-cypress-wp
        php_version: '7.3'
    - build-percy-cypress-wp-docker:
        <<: *only-master-filter
        name: chrome69-php7.2-percy-cypress-wp
        php_version: '7.2'

    - build-tiller-circleci-docker:
        <<: *only-master-filter
        name: node-10-tiller-circleci
        node_version: '10'
    - build-tiller-circleci-docker:
        <<: *only-master-filter
        name: node-12-tiller-circleci
        node_version: '12'

workflows:
  build-docker-nightly:
    <<: *build-docker-workflow
    triggers:
      - schedule:
          <<: *only-master-filter
          # Every day at 0600 UTC
          cron: "0 6 * * *"
          filters:
            branches:
              only: master

  build-docker-on-push:
    <<: *build-docker-workflow

  vaildate-orbs:
    jobs:
      - vaildate-orb:
          name: vaildate-composer-orb
          orb_path: 'src/composer/orb.yml'
      - vaildate-orb:
          name: vaildate-percy-cypress-wp-orb
          orb_path: 'src/percy-cypress-wp/orb.yml'
      - vaildate-orb:
          name: vaildate-tiller-circleci-orb
          orb_path: 'src/tiller-circleci/orb.yml'
      - vaildate-orb:
          name: vaildate-yarn-orb
          orb_path: 'src/yarn/orb.yml'
