version: 2.1

jobs:
  build-percy-anywhere-wp-docker:
    machine: true
    parameters:
      php_version:
        type: string
      ruby_version:
        type: string
    steps:
      - checkout
      - run: docker build --tag itinerisltd/percy-anywhere-wp:php-<< parameters.php_version >>-ruby-<< parameters.ruby_version >> --build-arg PHP_VERSION=<< parameters.php_version >> --build-arg RUBY_VERSION=<< parameters.ruby_version >> src/percy-anywhere-wp
      - run: echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - run: docker push itinerisltd/percy-anywhere-wp:php-<< parameters.php_version >>-ruby-<< parameters.ruby_version >>

  build-tiller-circleci-docker:
    machine: true
    parameters:
      node_version:
        type: string
      python_version:
        type: string
      ansible_version:
        type: string
    steps:
      - checkout
      - run: docker build --tag itinerisltd/tiller-circleci:ansible-<< parameters.ansible_version >>-python-<< parameters.python_version >>node-<< parameters.node_version >> --build-arg ANSIBLE_VERSION=<< parameters.ansible_version >> --build-arg PYTHON_VERSION=<< parameters.python_version >> --build-arg NODE_VERSION=<< parameters.node_version >> src/tiller-circleci
      - run: echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - run: docker push itinerisltd/tiller-circleci:ansible-<< parameters.ansible_version >>-python-<< parameters.python_version >>node-<< parameters.node_version >>

build-docker-workflow: &build-docker-workflow
  jobs:
    - build-percy-anywhere-wp-docker:
        name: php-7.3-ruby-2.6.1-percy-anywhere-wp
        php_version: '7.3'
        ruby_version: '2.6.1'
    - build-percy-anywhere-wp-docker:
        name: php-7.2-ruby-2.6.1-percy-anywhere-wp
        php_version: '7.2'
        ruby_version: '2.6.1'
    - build-percy-anywhere-wp-docker:
        name: php-7.1-ruby-2.6.1-percy-anywhere-wp
        php_version: '7.1'
        ruby_version: '2.6.1'

    - build-tiller-circleci-docker:
        name: ansible-latest-python-3-node-10-tiller-circleci
        ansible_version: 'latest'
        python_version: '3'
        node_version: '10'
    - build-tiller-circleci-docker:
        name: ansible-2.7-python-3-node-10-tiller-circleci
        ansible_version: '2.7'
        python_version: '3'
        node_version: '10'
    - build-tiller-circleci-docker:
        name: ansible-latest-python-2-node-10-tiller-circleci
        ansible_version: 'latest'
        python_version: '2'
        node_version: '10'
    - build-tiller-circleci-docker:
        name: ansible-2.7-python-2-node-10-tiller-circleci
        ansible_version: '2.7'
        python_version: '2'
        node_version: '10'

workflows:
  build-docker-nightly:
    <<: *build-docker-workflow
    triggers:
      - schedule:
          # Every day at 12am UTC
          cron: "0 0 * * *"
          filters:
            branches:
              only: master

  build-docker-on-push:
    <<: *build-docker-workflow
