version: 2.1

###################################################################################################
# GitHub: https://github.com/ItinerisLtd/circleci-orbs-wordpress/blob/master/src/composer/orb.yml #
# CircleCI: https://circleci.com/orbs/registry/orb/itinerisltd/composer                           #
###################################################################################################

description: |
  Wrapper for composer
  Source Code: https://github.com/ItinerisLtd/circleci-orbs-wordpress/blob/master/src/composer/orb.yml

commands:
  restore_composer_cache:
    parameters:
      working-dir: &working-dir
        type: string
        description: Working directory to use, path to composer project. Related to ~/project
        default: .
    steps:
      - restore_cache:
          keys:
            - v0.3-itinerisltd-composer-cache-<< parameters.working-dir >>-{{ arch }}-{{ .Branch }}-{{ .Revision }}-
            - v0.3-itinerisltd-composer-cache-<< parameters.working-dir >>-{{ arch }}-{{ .Branch }}-
            - v0.3-itinerisltd-composer-cache-<< parameters.working-dir >>-{{ arch }}-

  save_composer_cache:
    parameters:
      working-dir: *working-dir
    steps:
      - save_cache:
          key: v0.3-itinerisltd-composer-cache-<< parameters.working-dir >>-{{ arch }}-{{ .Branch }}-{{ .Revision }}-{{ epoch }}
          paths:
            - ~/.composer/cache
            - ~/project/<< parameters.working-dir >>/vendor

  exec:
    description: |
        Execute `$ composer --working-dir=<working-dir> xxx`
    parameters:
      working-dir: *working-dir
      command:
        type: string
        description: command to run (including its arguments except `--working-dir`)
    steps:
      - run: composer --working-dir=<< parameters.working-dir >> << parameters.command >>

jobs:
  install:
    description: |
      Run `$ composer install --prefer-dist --no-interaction` at `working-dir` with caching
    parameters:
      working-dir: *working-dir
      executor:
        type: executor
        default: latest
    executor: << parameters.executor >>
    working_directory: ~/project
    steps:
      - run: php --version
      - run: composer --version
      - checkout
      - restore_composer_cache:
          working-dir: << parameters.working-dir >>
      - exec:
          command: install --prefer-dist --no-interaction
          working-dir: << parameters.working-dir >>
      - save_composer_cache:
          working-dir: << parameters.working-dir >>

executors:
  latest:
    docker:
      - image: 'circleci/php:latest'
  php-7:
    docker:
      - image: 'circleci/php:7'
  php-73:
    docker:
      - image: 'circleci/php:7.3'
  php-72:
    docker:
      - image: 'circleci/php:7.2'

examples:
  style-check:
    description: |
      Execute `$ composer install && composer style:check` with PHP 7.2 at `web/app/themes/sage`
    usage:
      version: 2.1
      orbs:
        composer: itinerisltd/composer@volatile
      workflows:
        style-check:
          jobs:
            - composer/install:
                name: sage-style-check
                executor: composer/php-72
                working-dir: web/app/themes/sage
                post-steps:
                  - composer/exec:
                      command: style:check
                      working-dir: web/app/themes/sage
