version: 2.1

###############################################################################################
# GitHub: https://github.com/ItinerisLtd/circleci-orbs-wordpress/blob/master/src/yarn/orb.yml #
# CircleCI: https://circleci.com/orbs/registry/orb/itinerisltd/yarn                           #
###############################################################################################

description: |
  Wrapper for yarn
  Source Code: https://github.com/ItinerisLtd/circleci-orbs-wordpress/blob/master/src/yarn/orb.yml

commands:
  restore_yarn_cache:
    parameters:
      cwd: &cwd
        type: string
        description: Working directory to use, path to yarn project. Related to ~/project
        default: .
    steps:
      - restore_cache:
          keys:
            - v0.4-itinerisltd-yarn-cache-<< parameters.cwd >>-{{ arch }}-{{ .Branch }}-{{ .Revision }}-
            - v0.4-itinerisltd-yarn-cache-<< parameters.cwd >>-{{ arch }}-{{ .Branch }}-
            - v0.4-itinerisltd-yarn-cache-<< parameters.cwd >>-{{ arch }}-

  save_yarn_cache:
    parameters:
      cwd: *cwd
    steps:
      - save_cache:
          key: v0.4-itinerisltd-yarn-cache-<< parameters.cwd >>-{{ arch }}-{{ .Branch }}-{{ .Revision }}-{{ epoch }}
          paths:
            - ~/.yarn/cache
            - ~/project/<< parameters.cwd >>/node_modules

  exec:
    description: Execute `$ yarn yarn --cwd=<cwd> <command>`
    parameters:
      command:
        type: string
        description: command to run (including its arguments except --cwd)
      cwd: *cwd
    steps:
      - run: yarn --cwd=<< parameters.cwd >> << parameters.command >>

jobs:
  install:
    description: Run `$ yarn --cwd=<cwd> install --frozen-lockfile` caching
    parameters:
      cwd: *cwd
      executor:
        type: executor
        default: node-10
    executor: << parameters.executor >>
    working_directory: ~/project
    steps:
      - run: node --version
      - run: yarn versions
      - checkout
      - restore_yarn_cache:
          cwd: << parameters.cwd >>
      - exec:
          command: install --frozen-lockfile
          cwd: << parameters.cwd >>
      - save_yarn_cache:
          cwd: << parameters.cwd >>

executors:
  node-10:
    docker:
      - image: circleci/node:10

  node-12:
    docker:
      - image: circleci/node:12

examples:
  yarn-build:
    description: |
      Execute `$ yarn --cwd=web/app/themes/sage build:production` on NodeJS 12 with caching after `$ $ yarn --cwd=web/app/themes/sage install --frozen-lockfile`
    usage:
      version: 2.1
      orbs:
        yarn: itinerisltd/yarn@volatile
      workflows:
        yarn-build:
          jobs:
            - yarn/install:
                name: yarn-build
                executor: yarn/node-12
                working_dir: web/app/themes/sage
                post-steps:
                  - yarn/exec:
                      command: build:production
                      cwd: web/app/themes/sage
