version: 2.1

############################################################################################################
# GitHub: https://github.com/ItinerisLtd/circleci-orbs-wordpress/blob/master/src/percy-anywhere-wp/orb.yml #
# CircleCI: https://circleci.com/orbs/registry/orb/itinerisltd/percy-anywhere-wp                           #
############################################################################################################

description: |
  Take percy.io snapshots at Bedrock (WordPress) projects
  Source Code: https://github.com/ItinerisLtd/circleci-orbs-wordpress/blob/master/src/percy-anywhere-wp/orb.yml

jobs:
  snapshot:
    parameters:
      executor:
        type: executor
        default: default
      dot_env:
        type: string
        description: .env file that contain non-secret environment-specific variables
        default: .env.percy
    executor: << parameters.executor >>
    working_directory: ~/project
    environment:
      PERCY_DEBUG: '1'
      BUNDLE_PATH: bundle/vendor
    steps:
      - run: ruby --version
      - run: bundle --version
      - run: wp --info
      - run: which mysql
      - run: phantomjs --version
      - run: php --version
      - run: composer --version
      - restore_cache:
          keys:
            - v0-percy-bundle-cache-{{ arch }}-{{ .Branch }}-{{ .Revision }}-
            - v0-percy-bundle-cache-{{ arch }}-{{ .Branch }}-
            - v0-percy-bundle-cache-{{ arch }}-
      - run: bundle install --deployment --jobs=4 --retry=3
      - save_cache:
          key: v0-percy-bundle-cache-{{ arch }}-{{ .Branch }}-{{ .Revision }}-{{ epoch }}
          paths:
            - bundle/vendor
      - run: cp << parameters.dot_env >> .env
      - run: wp db reset --yes --skip-packages --skip-themes --skip-plugins
      - run: wp core install --url='http://localhost:8080' --title=Percy --admin_user=percy --admin_email='percy@circleci.test' --skip-email --skip-packages --skip-themes --skip-plugins

      # TODO: Allow using other database migration tools
      - run: wp plugin activate wp-migrate-db-pro wp-migrate-db-pro-cli --skip-packages --skip-themes --skip-plugins
      - run: wp migratedb pull $WP_MIGRATE_DB_URL $WP_MIGRATE_DB_SECRET_KEY
      - run: wp core update-db --skip-packages --skip-themes --skip-plugins
      - run: wp rewrite flush

executors:
  default:
    parameters:
      web_image:
        type: string
        default: 'itinerisltd/percy-anywhere-wp:php-7.3-ruby-2.6.1'
      db_image:
        type: string
        default: 'circleci/mariadb:latest-ram'
    docker:
        - image: << parameters.web_image >>
        - image: << parameters.db_image >>

examples:
  visual-test:
    description: |
      Build the Bedrock site (`composer install`, `yarn install` and `yarn build:production`) and take percy.io snapshots.
    usage:
      version: 2.1

      orbs:
        composer: itinerisltd/composer@0
        yarn: itinerisltd/yarn@0
        percy-anywhere-wp: itinerisltd/percy-anywhere-wp@0

      workflows:
        visual-test:
          jobs:
            - composer/install:
                name: bedrock-composer-install
                install_args: --no-dev --optimize-autoloader --prefer-dist --no-interaction
                post-steps:
                  - persist_to_workspace:
                      root: ~/project
                      paths:
                        - vendor
                        - web
            - composer/install:
                name: sage-composer-install
                install_args: --no-dev --optimize-autoloader --prefer-dist --no-interaction
                working_dir: web/app/themes/eelga
                post-steps:
                  - persist_to_workspace:
                      root: ~/project
                      paths:
                        - web/app/themes/eelga/vendor
            - yarn/install:
                name: sage-yarn-build
                cwd: web/app/themes/eelga
                post-steps:
                  - yarn/exec:
                      command: build:production
                      cwd: web/app/themes/eelga
                  - persist_to_workspace:
                      root: ~/project
                      paths:
                        - web/app/themes/eelga/dist
            - percy-anywhere-wp/snapshot:
                name: percy-snapshot
                pre-steps:
                  - checkout
                  - attach_workspace:
                      at: ~/project
                post-steps:
                  - run: bundle exec ruby percy.rb
                requires:
                  - bedrock-composer-install
                  - sage-composer-install
                  - sage-yarn-build
